Repository SW-CSS/sw-css, pull requests merged in 2024-08, with the labels that each got.

#124 Feature/#102 마일스톤 실적 승인 페이지 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/sw_css/admin/milestone/api/MilestoneHistoryAdminController.java
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminCommandService.java
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminQueryService.java
  backend/src/main/java/sw_css/admin/milestone/application/dto/response/MilestoneHistoryResponse.java
  backend/src/main/java/sw_css/file/api/FileController.java
  backend/src/main/java/sw_css/file/application/FileService.java
  backend/src/main/java/sw_css/milestone/application/MilestoneHistoryCommandService.java
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneScoreOfStudentResponse.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneHistory.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneHistorySearchField.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryCustomRepository.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryRepository.java
  backend/src/main/java/sw_css/milestone/exception/MilestoneHistoryExceptionType.java
  backend/src/main/java/sw_css/milestone/persistence/MilestoneHistoryCustomRepositoryImpl.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/http/milestone_history.http
  backend/src/test/java/sw_css/restdocs/RestDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/FileApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MilestoneHistoryApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
  frontend/src/app/(withSidebar)/my-page/components/MilestoneHistoryStatusLabel/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/styled.ts
  frontend/src/app/(withSidebar)/my-page/milestone/register/write/components/MilestoneDropdown/index.tsx
  frontend/src/app/admin/milestone/list/[slug]/components/FilePreview/index.tsx
  frontend/src/app/admin/milestone/list/[slug]/components/MilestoneHistoryStatusChangeButton/index.tsx
  frontend/src/app/admin/milestone/list/[slug]/page.tsx
  frontend/src/app/admin/milestone/list/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/admin/milestone/list/page.tsx
  frontend/src/app/components/Formik/Dropdown/index.tsx
  frontend/src/components/MilestoneGroupLabel/index.tsx
  frontend/src/data/milestone.ts
  frontend/src/data/queryKey.ts
  frontend/src/lib/api/server.api.ts
  frontend/src/lib/hooks/useAdminApi.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/utils/utils.tsx
  frontend/src/types/common.dto.ts
  frontend/tailwind.config.js
Labels: ✨ 기능 개발, 🌑 백엔드, 🌕 프론트엔드

#125 Feature/#106 rss로 공지사항 섹션 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/Announcement/index.tsx
  frontend/src/mocks/announcement.ts
  frontend/src/types/common.dto.ts
Labels: ✨ 기능 개발, 🌕 프론트엔드

#130 feat: 머지하기 전 front build test
  .github/workflows/front-buildtest.yml
  frontend/.gitignore
Labels: ⚙ 세팅, 🌕 프론트엔드

#132 fix: 빌드 테스트 오류 픽스
  .github/workflows/front-buildtest.yml
Labels: ⚙ 세팅, :lady_beetle: 버그, 🌕 프론트엔드

#134 feat: 머지 전, front build test 오류 픽스
  .github/workflows/front-buildtest.yml
Labels: ⚙ 세팅, :lady_beetle: 버그, 🌕 프론트엔드

#136 feat: 머지 전, front build test 오류 픽스
  .github/workflows/front-buildtest.yml
Labels: ⚙ 세팅, :lady_beetle: 버그, 🌕 프론트엔드

#138 feat: 머지 전, front build test 오류 픽스
  .github/workflows/front-buildtest.yml
Labels: ⚙ 세팅, :lady_beetle: 버그, 🌕 프론트엔드

#126 Feature/#104 마일스톤 실적 일괄등록 페이지 구현
  backend/src/main/java/sw_css/file/api/FileController.java
  backend/src/main/resources/static/files/history_register_sample.xlsx
  backend/src/main/resources/static/files/history_standard.pdf
  backend/src/test/java/sw_css/restdocs/docs/FileApiDocsTest.java
  frontend/.eslintrc.json
  frontend/public/images/admin/pdf_icon.svg
  frontend/src/app/(withSidebar)/my-page/components/MilestoneSection/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneDetail/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneOverview/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/page.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryDeleteButton/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
  frontend/src/app/admin/milestone/list/[slug]/components/MilestoneHistoryStatusChangeButton/index.tsx
  frontend/src/app/admin/milestone/register/page.tsx
  frontend/src/app/components/SignIn/components/InputUserInfo/index.tsx
  frontend/src/lib/api/client.axios.ts
  frontend/src/lib/hooks/useAdminApi.ts
  frontend/src/lib/hooks/useAxios.ts
  frontend/tailwind.config.js
Labels: ✨ 기능 개발, 🌕 프론트엔드

#143 feat: 머지하기 전, back build test
  .github/workflows/back-build-test.yml
Labels: ⚙ 세팅, 🌑 백엔드

#146 Feature/#119 마일스톤 목록 데이터를 엑셀 파일로 다운로드하는 기능
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/sw_css/admin/milestone/api/MilestoneHistoryAdminController.java
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminQueryService.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneGroup.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryCustomRepository.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneScoreRepository.java
  backend/src/main/java/sw_css/milestone/persistence/MilestoneHistoryCustomRepositoryImpl.java
  backend/src/main/java/sw_css/milestone/persistence/MilestoneScoreRepositoryImpl.java
  backend/src/main/resources/http/milestone_history.http
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
  frontend/src/app/admin/milestone/list/components/MilestoneHistoryTable/MilestoneHistoryExcelFileDownloadButton.tsx/index.tsx
  frontend/src/app/admin/milestone/list/page.tsx
  frontend/src/app/admin/milestone/rank/page.tsx
  frontend/src/data/queryKey.ts
  frontend/src/lib/hooks/useAdminApi.ts
Labels: ✨ 기능 개발, 🌑 백엔드, 🌕 프론트엔드

#142 Feature/#127 실적 등록 시 허용되는 파일 유형 제한하기
  backend/src/main/java/sw_css/milestone/application/MilestoneHistoryCommandService.java
  backend/src/main/java/sw_css/milestone/exception/MilestoneHistoryExceptionType.java
  backend/src/test/java/sw_css/restdocs/docs/MilestoneHistoryApiDocsTest.java
  frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
Labels: ✨ 기능 개발, 🌑 백엔드, 🌕 프론트엔드

#149 Feature/#141 예외 처리 코드 개선
  frontend/src/app/(withSidebar)/my-page/components/MilestoneHistorySection/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/StudentInfoSection/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneOverview/index.tsx
  frontend/src/app/CustomLayout.tsx
  frontend/src/app/admin/milestone/list/[slug]/not-found.tsx
  frontend/src/app/admin/milestone/list/[slug]/page.tsx
  frontend/src/app/admin/milestone/list/components/MilestoneHistoryTable/MilestoneHistoryExcelFileDownloadButton.tsx/index.tsx
  frontend/src/app/admin/milestone/list/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/admin/milestone/list/page.tsx
  frontend/src/app/admin/milestone/rank/page.tsx
  frontend/src/app/admin/milestone/register/page.tsx
Labels: :art: 디자인, :lady_beetle: 버그, 🌕 프론트엔드

#151 Feature/#150 학생의 마일스톤 획득내역 실적목록 페이지네이션 처리
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneHistoryOfStudentResponse.java
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/page.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/page.tsx
  frontend/src/app/components/Pagination/index.tsx
Labels: ✨ 기능 개발, 🌕 프론트엔드

#157 Feature/#155 url로 파일 리소스에 접근할 수 있도록 설정
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/sw_css/config/ResourceConfig.java
  backend/src/main/java/sw_css/file/api/FileController.java
  backend/src/main/java/sw_css/file/application/FileService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/sw_css/restdocs/docs/FileApiDocsTest.java
Labels: ✨ 기능 개발, 🌑 백엔드

#161 Feature/#109 member 관련 api 구현
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/sw_css/SwCssApplication.java
  backend/src/main/java/sw_css/auth/api/SignInController.java
  backend/src/main/java/sw_css/auth/api/SignUpController.java
  backend/src/main/java/sw_css/auth/application/AuthCheckDuplicateService.java
  backend/src/main/java/sw_css/auth/application/AuthEmailService.java
  backend/src/main/java/sw_css/auth/application/AuthSignInService.java
  backend/src/main/java/sw_css/auth/application/AuthSignUpService.java
  backend/src/main/java/sw_css/auth/application/dto/request/ResetPasswordRequest.java
  backend/src/main/java/sw_css/auth/application/dto/request/SendAuthCodeRequest.java
  backend/src/main/java/sw_css/auth/application/dto/request/SignInRequest.java
  backend/src/main/java/sw_css/auth/application/dto/request/SignUpRequest.java
  backend/src/main/java/sw_css/auth/application/dto/response/CheckDuplicateResponse.java
  backend/src/main/java/sw_css/auth/application/dto/response/SendAuthCodeResponse.java
  backend/src/main/java/sw_css/auth/application/dto/response/SignInResponse.java
  backend/src/main/java/sw_css/auth/domain/EmailAuthRedis.java
  backend/src/main/java/sw_css/auth/domain/repository/EmailAuthRedisRepository.java
  backend/src/main/java/sw_css/auth/exception/AuthException.java
  backend/src/main/java/sw_css/auth/exception/AuthExceptionType.java
  backend/src/main/java/sw_css/config/RedisConfig.java
  backend/src/main/java/sw_css/config/WebConfig.java
  backend/src/main/java/sw_css/member/api/MemberController.java
  backend/src/main/java/sw_css/member/application/MemberQueryService.java
  backend/src/main/java/sw_css/member/application/dto/request/ChangePasswordRequest.java
  backend/src/main/java/sw_css/member/domain/Member.java
  backend/src/main/java/sw_css/member/domain/Role.java
  backend/src/main/java/sw_css/member/domain/embedded/EmailAddress.java
  backend/src/main/java/sw_css/member/domain/embedded/Password.java
  backend/src/main/java/sw_css/member/domain/embedded/PhoneNumber.java
  backend/src/main/java/sw_css/member/domain/embedded/RealName.java
  backend/src/main/java/sw_css/member/domain/embedded/StudentId.java
  backend/src/main/java/sw_css/member/domain/repository/FacultyMemberRepository.java
  backend/src/main/java/sw_css/member/domain/repository/MemberRepository.java
  backend/src/main/java/sw_css/member/domain/repository/StudentMemberRepository.java
  backend/src/main/java/sw_css/member/exception/MemberExceptionType.java
  backend/src/main/java/sw_css/utils/JwtToken/JwtAuthorizationArgumentResolver.java
  backend/src/main/java/sw_css/utils/JwtToken/JwtTokenProvider.java
  backend/src/main/java/sw_css/utils/JwtToken/JwtUserDetails.java
  backend/src/main/java/sw_css/utils/JwtToken/exception/JwtTokenException.java
  backend/src/main/java/sw_css/utils/JwtToken/exception/JwtTokenExceptionType.java
  backend/src/main/java/sw_css/utils/MailUtil.java
  backend/src/main/java/sw_css/utils/RedisUtil.java
  backend/src/main/java/sw_css/utils/annotation/JwtAuthorization.java
  backend/src/main/resources/static/docs/index.html
  backend/src/main/resources/test-data.sql
  backend/src/test/java/sw_css/restdocs/RestDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MemberApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/SignInApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/SignUpApiDocsTest.java
Labels: 📬 API, 🌑 백엔드

#166 Feature/#164 로그인 및 회원가입 api 연결
  backend/src/main/java/sw_css/auth/application/AuthEmailService.java
  backend/src/main/java/sw_css/auth/application/AuthSignInService.java
  backend/src/main/java/sw_css/auth/application/AuthSignUpService.java
  backend/src/main/java/sw_css/auth/application/dto/response/SignInResponse.java
  backend/src/test/java/sw_css/restdocs/docs/SignInApiDocsTest.java
  frontend/src/adminComponents/Header/components/UserName/index.tsx
  frontend/src/adminComponents/Header/index.tsx
  frontend/src/app/(auth)/sign-in/components/InputUserInfo/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/components/EmailTextInput/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/index.tsx
  frontend/src/app/(auth)/sign-up/page.tsx
  frontend/src/app/(auth)/styled.ts
  frontend/src/app/(withSidebar)/my-page/components/MilestoneHistorySection/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/MilestoneSection/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/StudentInfoSection/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneDetail/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneOverview/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/admin/milestone/list/[slug]/page.tsx
  frontend/src/app/admin/milestone/list/page.tsx
  frontend/src/app/components/ExternalLink/index.tsx
  frontend/src/app/components/PnuLink/index.tsx
  frontend/src/app/components/SignIn/components/InputUserInfo/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/data/queryKey.ts
  frontend/src/data/signUp.ts
  frontend/src/lib/api/server.api.ts
  frontend/src/lib/api/server.axios.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/utils/utils.tsx
  frontend/src/store/auth.slice.ts
  frontend/src/types/error.ts
Labels: ✨ 기능 개발, 📬 API, 🌕 프론트엔드

#158 Feature/#152 해커톤 페이지 구현
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(withSidebar)/hackathon/page.tsx
  frontend/src/app/(withSidebar)/hackathon/sw-hackathon/page.tsx
  frontend/src/app/(withSidebar)/milestone/page.tsx
  frontend/src/app/(withSidebar)/milestone/styled.ts
  frontend/src/components/Title/index.tsx
  frontend/src/data/clientCategory.ts
  frontend/src/data/hackathon.ts
  frontend/src/lib/api/server.api.ts
  frontend/src/types/common.dto.ts
Labels: ✨ 기능 개발, 🌕 프론트엔드

#159 Feature/#156 마일스톤 페이지 내 파일 접근 방식 수정
  frontend/src/app/admin/milestone/list/[slug]/components/FilePreview/index.tsx
  frontend/src/app/admin/milestone/register/page.tsx
  frontend/src/lib/api/server.api.ts
  frontend/src/lib/hooks/useApi.ts
Labels: :lady_beetle: 버그, 🌕 프론트엔드

#167 Feature/#160 해커톤 단건 조회 페이지 구현
  backend/src/main/resources/schema.sql
  backend/src/main/resources/test-data.sql
  frontend/.babelrc
  frontend/babel.config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/adminComponents/Header/index.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/components/HackathonInformationTypeButtons/index.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/layout.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/page.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/prize/page.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/vote/components/HackathonTeamCreateModal/index.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/vote/components/HackathonTeamReadModal/index.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/vote/components/ReadmeViewer/index.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/vote/components/TeamCreateInputSection/index.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/vote/components/TeamMemberInput/index.tsx
  frontend/src/app/(withSidebar)/hackathon/[slug]/vote/page.tsx
  frontend/src/app/(withSidebar)/hackathon/page.tsx
  frontend/src/app/admin/milestone/list/page.tsx
  frontend/src/components/Formik/Dropdown/index.tsx
  frontend/src/components/Formik/ImageUploader/index.tsx
  frontend/src/components/Formik/TextInput/index.tsx
  frontend/src/components/MarkdownViewer/index.tsx
  frontend/src/components/MarkdownViewer/markdown.css
  frontend/src/components/Title/index.tsx
  frontend/src/data/hackathon.ts
  frontend/src/data/queryKey.ts
  frontend/src/lib/api/github.axios.ts
  frontend/src/lib/api/server.api.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/hooks/useBodyScrollLock.ts
  frontend/src/lib/hooks/useDebounce.ts
  frontend/src/lib/hooks/useDivSize.ts
  frontend/src/lib/hooks/useGithubReadme.ts
  frontend/src/lib/hooks/useOnClickOutside.ts
  frontend/src/mocks/hackathon.ts
  frontend/src/types/common.dto.ts
  frontend/tailwind.config.js
Labels: ✨ 기능 개발, 🌕 프론트엔드

#169 Feature/#168 로그인api 반환 값 변경
  backend/src/main/java/sw_css/auth/application/AuthSignInService.java
  backend/src/main/java/sw_css/auth/application/dto/response/SignInResponse.java
  backend/src/main/java/sw_css/member/domain/repository/FacultyMemberRepository.java
  backend/src/main/java/sw_css/member/domain/repository/StudentMemberRepository.java
  backend/src/main/resources/schema.sql
  backend/src/main/resources/test-data.sql
Labels: ✨ 기능 개발, 🌑 백엔드

#174 Feature/#173 깃 액션 빌드조건 변경
  .github/workflows/back-build-test.yml
  .github/workflows/front-build-test.yml
Labels: ⚙ 세팅

#178 Feature/#175 test 및 application 수정
  backend/src/test/java/sw_css/SwCssApplicationTests.java
Labels: ⚙ 세팅, 🌑 백엔드
