Repository SW-CSS/sw-css, pull requests merged in 2024-07, with the labels that each got.

#68 Feature/#67 Hibernate 초기화 순서 변경
  backend/src/main/resources/application.yml
Labels: :lady_beetle: 버그, 🌑 백엔드

#70 Feature/#69 tailwind 설치
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/globals.css
  frontend/tailwind.config.js
Labels: ⚙ 세팅, 🌕 프론트엔드

#72 Feature/#71 tailwind 반응형 사이즈 커스텀
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/app/globals.css
  frontend/tailwind.config.js
Labels: ⚙ 세팅, 🌕 프론트엔드

#74 Feature/#73 tailwind class 자동 정렬
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
Labels: ⚙ 세팅, 🌕 프론트엔드

#76 Feature/#75 페이지 타이틀 컴포넌트 구현
  frontend/src/app/components/PageTitle/index.tsx
Labels: :art: 디자인, 🌕 프론트엔드

#65 Feature/#25 마이페이지 마일스톤 획득 내역 페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(withSidebar)/milestone/page.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneDetail/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneDetail/styled.ts
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/styled.ts
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneOverview/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneOverview/styled.ts
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestonePeriodSearchForm/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestonePeriodSearchForm/styled.ts
  frontend/src/app/(withSidebar)/my-page/milestone/page.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/page.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/styled.ts
  frontend/src/app/(withSidebar)/my-page/page.tsx
  frontend/src/app/components/Milestone/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/MilestoneChart/index.tsx
  frontend/src/components/MilestoneChart/styled.ts
  frontend/src/components/MilestoneTable/index.tsx
  frontend/src/constants.ts
  frontend/src/data/clientCategory.ts
  frontend/src/data/milestoneGroup.ts
  frontend/src/data/queryKey.ts
  frontend/src/lib/api/client.axios.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/hooks/useAxios.ts
  frontend/src/mocks/milestone.ts
  frontend/src/types/common.dto.ts
  frontend/src/types/common.ts
  frontend/src/types/milestone.ts
Labels: ✨ 기능 개발, 🌕 프론트엔드

#79 Feature/#78 기능 명세에 따른 API 명세 수정
  backend/src/main/java/sw_css/milestone/api/MilestoneHistoryController.java
  backend/src/main/java/sw_css/milestone/application/MilestoneHistoryQueryService.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryRepository.java
  backend/src/main/resources/test-data.sql
  backend/src/test/java/sw_css/restdocs/docs/MilestoneHistoryApiDocsTest.java
Labels: :lady_beetle: 버그, 🌑 백엔드

#81 Feature/#80 마일스톤 실적 조회 시 삭제되지 않은 실적만 조회되도록 수정
  backend/src/main/java/sw_css/milestone/domain/MilestoneHistory.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryRepository.java
Labels: ✨ 기능 개발, 📬 API, 🌑 백엔드

#77 Feature/#53 회원가입 페이지 구현
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/components/EmailTextInput/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/components/MajorDropdown/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/index.tsx
  frontend/src/app/(auth)/sign-up/page.tsx
  frontend/src/app/components/Formik/Dropdown/index.tsx
  frontend/src/app/components/Formik/TextInput/index.tsx
  frontend/src/components/Header/styled.ts
  frontend/src/data/signUp.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/hooks/useDivSize.ts
  frontend/src/mocks/college.ts
  frontend/src/types/common.dto.ts
  frontend/tailwind.config.js
Labels: :art: 디자인, ✨ 기능 개발, 🌕 프론트엔드

#85 Feature/#84 충돌 에러 픽스
  frontend/src/app/(auth)/sign-up/page.tsx
  frontend/src/components/Sidebar/index.tsx
  frontend/src/components/Sidebar/styled.ts
  frontend/src/lib/hooks/useApi.ts
Labels: :lady_beetle: 버그, 🌕 프론트엔드

#88 Feature/#87 비밀번호 찾는 페이지 구현
  frontend/src/app/(auth)/find-password/components/FindForm/index.tsx
  frontend/src/app/(auth)/find-password/page.tsx
  frontend/src/app/(auth)/sign-in/page.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/components/MajorDropdown/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/index.tsx
  frontend/src/app/(auth)/sign-up/page.tsx
  frontend/src/app/components/Formik/Dropdown/index.tsx
  frontend/src/app/components/Formik/EmailTextInput/index.tsx
  frontend/src/app/components/Formik/TextInput/index.tsx
  frontend/src/app/components/SignIn/index.tsx
Labels: :art: 디자인, 🌕 프론트엔드

#90 Feature/#89 formik 관련 컴포넌트 폴더 위치 이동
  frontend/src/app/(auth)/find-password/components/FindForm/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/components/MajorDropdown/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/index.tsx
  frontend/src/components/Formik/Dropdown/index.tsx
  frontend/src/components/Formik/EmailTextInput/index.tsx
  frontend/src/components/Formik/TextInput/index.tsx
Labels: 🔨 리팩토링, 🌕 프론트엔드

#93 Feature/#92 dropdown 및 text input size props 추가
  frontend/src/components/Formik/Dropdown/index.tsx
  frontend/src/components/Formik/TextInput/index.tsx
  frontend/src/constants.ts
Labels: ✨ 기능 개발, 🌕 프론트엔드

#95 Feature/#94 dropdown 및 text input의 props 수정
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/components/MajorDropdown/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/index.tsx
  frontend/src/components/Formik/Dropdown/index.tsx
  frontend/src/components/Formik/TextInput/index.tsx
Labels: :art: 디자인, ✨ 기능 개발, 🌕 프론트엔드

#100 Feature/#48 회원 정보 조회 api 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/sw_css/admin/member/api/MemberAdminController.java
  backend/src/main/java/sw_css/admin/member/application/MemberAdminQueryService.java
  backend/src/main/java/sw_css/member/api/MemberController.java
  backend/src/main/java/sw_css/member/application/MemberQueryService.java
  backend/src/main/java/sw_css/member/application/dto/response/StudentMemberResponse.java
  backend/src/main/java/sw_css/member/domain/CareerType.java
  backend/src/main/java/sw_css/member/domain/StudentMember.java
  backend/src/main/resources/http/member.http
  backend/src/main/resources/test-data.sql
  backend/src/test/java/sw_css/restdocs/RestDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MemberApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MilestoneHistoryApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/admin/MemberAdminApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
Labels: ✨ 기능 개발, 🌑 백엔드

#96 Feature/#91 회원 계정 관리 페이지 구현
  frontend/src/adminComponents/Header/styled.ts
  frontend/src/adminComponents/Pagination/index.tsx
  frontend/src/adminComponents/Sidebar/styled.ts
  frontend/src/adminConstants.ts
  frontend/src/app/CustomLayout.tsx
  frontend/src/app/admin/member/list/components/MemberTable/index.tsx
  frontend/src/app/admin/member/list/components/SearchBox/index.tsx
  frontend/src/app/admin/member/list/page.tsx
  frontend/src/app/admin/member/page.tsx
  frontend/src/app/layout-styled.ts
  frontend/src/components/Formik/Dropdown/index.tsx
  frontend/src/components/Formik/TextInput/index.tsx
  frontend/src/mocks/adminMember.ts
  frontend/src/types/common.dto.ts
  frontend/tailwind.config.js
Labels: :art: 디자인, ✨ 기능 개발, 🌕 프론트엔드

#112 Feature/#110 api 페이지네이션 처리
  backend/build.gradle
  backend/src/main/java/sw_css/admin/milestone/api/MilestoneHistoryAdminController.java
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminQueryService.java
  backend/src/main/java/sw_css/admin/milestone/application/dto/response/MilestoneHistoryResponse.java
  backend/src/main/java/sw_css/admin/milestone/persistence/StudentAndMilestoneScoreInfo.java
  backend/src/main/java/sw_css/config/QueryDslConfig.java
  backend/src/main/java/sw_css/milestone/api/MilestoneHistoryController.java
  backend/src/main/java/sw_css/milestone/application/MilestoneHistoryQueryService.java
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneHistoryOfStudentResponse.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneHistory.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneHistorySortCriteria.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryCustomRepository.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryRepository.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneScoreRepository.java
  backend/src/main/java/sw_css/milestone/persistence/MilestoneHistoryCustomRepositoryImpl.java
  backend/src/main/java/sw_css/milestone/persistence/MilestoneScoreRepositoryImpl.java
  backend/src/main/resources/http/milestone_history.http
  backend/src/main/resources/test-data.sql
  backend/src/test/java/sw_css/restdocs/docs/MilestoneHistoryApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
Labels: ✨ 기능 개발, 🌑 백엔드

#115 Hotfix/#114 깨지는 테스트 오류 해결
  backend/src/main/resources/test-data.sql
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
Labels: :lady_beetle: 버그, 🌑 백엔드

#99 Feature/#26 마일스톤 실적등록 페이지 구현
  frontend/package.json
  frontend/src/adminComponents/Pagination/index.tsx
  frontend/src/app/(auth)/sign-in/components/InputUserInfo/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/components/EmailTextInput/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpFirstPage/index.tsx
  frontend/src/app/(auth)/sign-up/components/SignUpSecondPage/index.tsx
  frontend/src/app/(auth)/sign-up/page.tsx
  frontend/src/app/(withSidebar)/my-page/components/MilestoneHistorySection/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/MilestoneHistoryStatusLabel/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/MilestoneRowBarTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/MilestoneSection/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/StudentInfoSection/StudentInfoLabel/index.tsx
  frontend/src/app/(withSidebar)/my-page/components/StudentInfoSection/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneDetail/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/styled.ts
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneOverview/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/page.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryDeleteButton/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/page.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/write/components/MilestoneDropdown/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
  frontend/src/app/(withSidebar)/my-page/page.tsx
  frontend/src/app/admin/member/list/components/MemberTable/index.tsx
  frontend/src/app/admin/member/list/page.tsx
  frontend/src/app/components/Formik/DatePicker/index.tsx
  frontend/src/app/components/Formik/Dropdown/index.tsx
  frontend/src/app/components/Formik/FileUploader/index.tsx
  frontend/src/app/components/Formik/TextInput/index.tsx
  frontend/src/app/components/PageTitle/index.tsx
  frontend/src/components/SearchBox/index.tsx
  frontend/src/components/SubTitle/index.tsx
  frontend/src/data/milestone.ts
  frontend/src/data/queryKey.ts
  frontend/src/lib/api/server.api.ts
  frontend/src/lib/api/server.axios.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/utils/utils.ts
  frontend/src/lib/utils/utils.tsx
  frontend/src/store/auth.slice.ts
  frontend/src/types/common.dto.ts
  frontend/src/types/milestone.ts
  frontend/tailwind.config.js
Labels: ✨ 기능 개발, 🌕 프론트엔드

#101 Feature/#24 마이페이지 구현
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneScoreOfStudentResponse.java
  frontend/src/app/(withSidebar)/my-page/components/MilestoneHistorySection/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
Labels: ✨ 기능 개발, 🌕 프론트엔드

#120 Feature/#103 모든 학생의 마일스톤 실적 현황 조회 페이지 구현
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminQueryService.java
  backend/src/main/java/sw_css/admin/milestone/application/dto/response/MilestoneScoreResponse.java
  backend/src/main/java/sw_css/milestone/api/MilestoneController.java
  backend/src/main/java/sw_css/milestone/application/MilestoneQueryService.java
  backend/src/main/resources/static/docs/index.html
  backend/src/test/java/sw_css/restdocs/docs/MilestoneApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
  frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
  frontend/src/app/(withSidebar)/my-page/milestone/page.tsx
  frontend/src/app/admin/milestone/rank/page.tsx
  frontend/src/components/MilestonePeriodSearchForm/index.tsx
  frontend/src/components/MilestonePeriodSearchForm/styled.ts
  frontend/src/data/queryKey.ts
  frontend/src/lib/hooks/useAdminApi.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/utils/utils.tsx
  frontend/src/types/common.dto.ts
  frontend/tailwind.config.js
Labels: :art: 디자인, ✨ 기능 개발, 🌕 프론트엔드
