Repository SW-CSS/sw-css, pull requests merged in 2024-06, with the labels that each got.

#13 Feature/#12 layout 수정
  frontend/next.config.mjs
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/styled.ts
  frontend/src/theme/StyledComponentsRegistry/index.tsx
Labels: ⚙ 세팅, :art: 디자인

#21 Feature/#8 마일스톤 실적관리 기능 구현
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/index.html
  backend/src/main/java/sw_css/admin/milestone/api/MilestoneHistoryAdminController.java
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminCommandService.java
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminQueryService.java
  backend/src/main/java/sw_css/admin/milestone/application/dto/request/MilestoneHistoryRejectRequest.java
  backend/src/main/java/sw_css/admin/milestone/application/dto/response/MilestoneHistoryResponse.java
  backend/src/main/java/sw_css/admin/milestone/domain/MilestoneHistoryExcelData.java
  backend/src/main/java/sw_css/config/JpaAuditingConfig.java
  backend/src/main/java/sw_css/major/api/MajorController.java
  backend/src/main/java/sw_css/major/domain/repository/CollegeRepository.java
  backend/src/main/java/sw_css/major/domain/repository/MajorRepository.java
  backend/src/main/java/sw_css/member/application/dto/response/StudentMemberReferenceResponse.java
  backend/src/main/java/sw_css/member/domain/FacultyMember.java
  backend/src/main/java/sw_css/member/domain/StudentMember.java
  backend/src/main/java/sw_css/member/domain/repository/StudentMemberRepository.java
  backend/src/main/java/sw_css/member/exception/MemberException.java
  backend/src/main/java/sw_css/member/exception/MemberExceptionType.java
  backend/src/main/java/sw_css/milestone/api/MilestoneHistoryController.java
  backend/src/main/java/sw_css/milestone/application/MilestoneCommandService.java
  backend/src/main/java/sw_css/milestone/application/MilestoneHistoryCommandService.java
  backend/src/main/java/sw_css/milestone/application/MilestoneHistoryQueryService.java
  backend/src/main/java/sw_css/milestone/application/dto/request/MilestoneHistoryCreateRequest.java
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneHistoryOfStudentResponse.java
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneReferenceResponse.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneCategory.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneGroup.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneHistory.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneStatus.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryRepository.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneRepository.java
  backend/src/main/java/sw_css/milestone/exception/MilestoneException.java
  backend/src/main/java/sw_css/milestone/exception/MilestoneExceptionType.java
  backend/src/main/java/sw_css/milestone/exception/MilestoneHistoryException.java
  backend/src/main/java/sw_css/milestone/exception/MilestoneHistoryExceptionType.java
  backend/src/main/java/sw_css/milestone/persistence/dto/MilestoneHistoryWithStudentInfo.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/http/major.http
  backend/src/main/resources/http/milestone_history.http
  backend/src/main/resources/schema.sql
  backend/src/main/resources/static/docs/index.html
  backend/src/main/resources/test-data.sql
  backend/src/test/java/sw_css/restdocs/RestDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MajorApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MilestoneHistoryApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
Labels: ✨ 기능 개발, 🌑 백엔드

#22 Feature/#9 마일스톤 점수 관리 기능 구현
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/sw_css/admin/milestone/api/MilestoneHistoryAdminController.java
  backend/src/main/java/sw_css/admin/milestone/application/MilestoneHistoryAdminQueryService.java
  backend/src/main/java/sw_css/admin/milestone/application/dto/response/MilestoneHistoryResponse.java
  backend/src/main/java/sw_css/admin/milestone/application/dto/response/MilestoneScoreResponse.java
  backend/src/main/java/sw_css/admin/milestone/persistence/StudentAndMilestoneHistoryInfo.java
  backend/src/main/java/sw_css/member/application/dto/response/StudentMemberReferenceResponse.java
  backend/src/main/java/sw_css/milestone/api/MilestoneController.java
  backend/src/main/java/sw_css/milestone/api/MilestoneHistoryController.java
  backend/src/main/java/sw_css/milestone/application/MilestoneCommandService.java
  backend/src/main/java/sw_css/milestone/application/MilestoneHistoryQueryService.java
  backend/src/main/java/sw_css/milestone/application/MilestoneQueryService.java
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneResponse.java
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestoneScoreOfStudentResponse.java
  backend/src/main/java/sw_css/milestone/application/dto/response/MilestonesByCategoryResponse.java
  backend/src/main/java/sw_css/milestone/domain/MilestoneCategory.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneCategoryRepository.java
  backend/src/main/java/sw_css/milestone/domain/repository/MilestoneHistoryRepository.java
  backend/src/main/java/sw_css/milestone/exception/MilestoneHistoryExceptionType.java
  backend/src/main/java/sw_css/milestone/persistence/dto/MilestoneHistoryInfo.java
  backend/src/main/java/sw_css/milestone/persistence/dto/MilestoneHistoryWithStudentInfo.java
  backend/src/main/resources/http/milestone.http
  backend/src/main/resources/http/milestone_history.http
  backend/src/main/resources/test-data.sql
  backend/src/test/java/sw_css/restdocs/RestDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MilestoneApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/MilestoneHistoryApiDocsTest.java
  backend/src/test/java/sw_css/restdocs/docs/admin/MilestoneHistoryAdminApiDocsTest.java
Labels: ✨ 기능 개발, 🌑 백엔드

#29 Feature/#27 카테고리별 하위경로에 대한 네비게이션바 제작
  .gitignore
  frontend/.eslintrc.json
  frontend/src/app/(withSidebar)/hackathon/page.tsx
  frontend/src/app/(withSidebar)/hackathon/sw-contest/page.tsx
  frontend/src/app/(withSidebar)/hackathon/sw-hackathon/page.tsx
  frontend/src/app/(withSidebar)/layout.tsx
  frontend/src/app/(withSidebar)/milestone/page.tsx
  frontend/src/app/(withSidebar)/milestone/styled.ts
  frontend/src/app/(withSidebar)/styled.ts
  frontend/src/app/layout-styled.ts
  frontend/src/app/styled.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styled.ts
  frontend/src/components/SideBar/index.tsx
  frontend/src/components/SideBar/styled.ts
  frontend/src/constants.ts
  frontend/src/store/index.ts
  frontend/src/store/provider.tsx
  frontend/src/types.ts
Labels: ✨ 기능 개발, 🌕 프론트엔드

#30 Feature/#17 에러 핸들링 코드 작성
  backend/src/main/java/sw_css/GlobalControllerAdvice.java
  backend/src/main/java/sw_css/config/CorsConfig.java
  backend/src/main/resources/application.yml
Labels: ⚙ 세팅, 🌑 백엔드

#40 Feature/#34 메인페이지 로그인 컴포넌트 구현
  frontend/src/app/components/Milestone/index.tsx
  frontend/src/app/components/SignIn/components/InputUserInfo/index.tsx
  frontend/src/app/components/SignIn/components/InputUserInfo/styled.ts
  frontend/src/app/components/SignIn/index.tsx
  frontend/src/app/components/SignIn/styled.ts
  frontend/src/app/components/styled.ts
  frontend/src/app/page.tsx
  frontend/src/app/styled.ts
  frontend/src/components/Header/styled.ts
  frontend/src/constants.ts
  frontend/src/store/index.ts
  frontend/src/store/provider.tsx
Labels: :art: 디자인, 🌕 프론트엔드

#46 Fix/#45 머지되면서 생긴 오류 픽스
  frontend/src/app/styled.ts
  frontend/src/components/IconButton/index.tsx
  frontend/src/types.ts
Labels: :lady_beetle: 버그, ✨ 기능 개발, 🌕 프론트엔드

#47 Feature/#37 메인페이지 외부 링커 컴포넌트 구현
  frontend/public/pngs/external_link_1_onestop.png
  frontend/public/pngs/external_link_2_plato.png
  frontend/public/pngs/external_link_3_edwith.png
  frontend/public/pngs/external_link_4_topcit.png
  frontend/public/pngs/external_link_5_pnu_achieve.png
  frontend/public/pngs/external_link_6_pnu_oj.png
  frontend/src/app/components/ExternalLink/index.tsx
  frontend/src/app/components/ExternalLink/styled.ts
  frontend/src/app/page.tsx
  frontend/src/constants.ts
  frontend/src/data/externalLink.ts
Labels: :art: 디자인, 🌕 프론트엔드

#31 Feature/#23 마일스톤 정보조회 페이지
  frontend/public/images/milestone_img01.png
  frontend/public/images/milestone_img02.png
  frontend/public/images/milestone_img02_bg.png
  frontend/public/images/milestone_img03.png
  frontend/src/app/(withSidebar)/milestone/page.tsx
  frontend/src/app/(withSidebar)/milestone/styled.ts
Labels: :art: 디자인, 🌕 프론트엔드

#49 Feature/#38 메인페이지 팀빌딩 컴포넌트 구현
  frontend/public/pngs/team_type_img_1.png
  frontend/public/pngs/team_type_img_2.png
  frontend/public/pngs/team_type_img_3.png
  frontend/public/pngs/team_type_img_4.png
  frontend/src/app/components/TeamBuildings/index.tsx
  frontend/src/app/components/TeamBuildings/styled.ts
  frontend/src/app/page.tsx
  frontend/src/components/TeamBuilding/index.tsx
  frontend/src/components/TeamBuilding/styled.ts
  frontend/src/constants.ts
  frontend/src/mocks/teamBuilding.ts
  frontend/src/types.ts
Labels: :art: 디자인, 🌕 프론트엔드

#51 Feature/#39 메인페이지 부산대 링크 스와이퍼 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/svgs/pnu_link_banner_1.svg
  frontend/public/svgs/pnu_link_banner_2.svg
  frontend/public/svgs/pnu_link_banner_3.svg
  frontend/public/svgs/pnu_link_banner_4.svg
  frontend/public/svgs/pnu_link_banner_5.svg
  frontend/public/svgs/pnu_link_banner_6.svg
  frontend/public/svgs/pnu_link_banner_7.svg
  frontend/src/app/components/PnuLink/index.tsx
  frontend/src/app/components/PnuLink/styled.ts
  frontend/src/app/page.tsx
  frontend/src/data/externalLink.ts
Labels: :art: 디자인, 🌕 프론트엔드

#55 Feature/#52 로그인페이지 구현
  frontend/src/app/(auth)/sign-in/components/InputUserInfo/index.tsx
  frontend/src/app/(auth)/sign-in/page.tsx
  frontend/src/app/(auth)/sign-in/styled.ts
  frontend/src/app/(auth)/styled.ts
  frontend/src/constants.ts
Labels: :art: 디자인, 🌕 프론트엔드

#64 Feature/#63 CORS 설정 추가
  backend/src/main/java/sw_css/config/CorsConfig.java
Labels: ⚙ 세팅, 🌑 백엔드

#62 Feature/#50 리액트 쿼리 셋팅
  frontend/.gitignore
  frontend/babel.config.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(auth)/sign-in/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/components/Header/HeaderAccordion/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/MilestoneChart/index.tsx
  frontend/src/data/adminCategory.ts
  frontend/src/data/queryKey.ts
  frontend/src/lib/api/client.axios.ts
  frontend/src/lib/hooks/useApi.ts
  frontend/src/lib/hooks/useAxios.ts
  frontend/src/lib/utils/reactQueryProvider.tsx
  frontend/src/lib/utils/utils.ts
  frontend/src/mocks/announcement.ts
  frontend/src/mocks/milestone.ts
  frontend/src/types/dto.ts
  frontend/src/types/error.ts
Labels: ⚙ 세팅, 🌕 프론트엔드
